
services:

  backend:
    build: ./go-application
    cpus: 0.25
    depends_on:
      - redis
    environment:
      TG_BOT_TOKEN: ""
      TG_CHANNEL: ""
    mem_limit: "64M"

  frontend:
    build: ./react-application
    cpus: 1
    depends_on:
      - backend
    mem_limit: "256M"
    ports:
      - "127.0.0.1:8080:8080"

  redis:
    cpus: 0.25
    image: redis:7.4.0-alpine
    mem_limit: "64M"
    volumes:
      - ./redis_data:/data
